# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - sui move build
      - echo "build done"
    sources:
      - sources/**/*.move
      - Move.toml
  demo:
    deps:
      - build
    cmds:
      - yarn ts-node demo/suiadrop.ts
    sources:
      - demo/**/*.ts
      - .env
